### ISSUE TITLE
upload or include from a url

### ISSUE THREAD

**Issue by jcw** [jeelabs/folie#10]
There's no reason why folie should be limited to embedded and local files for both include (#2) and upload (#3) requests - it could also accept a URL, fetch it. and use that contents instead.

**Comment by JohnOH** [comment]
Great idea, starters don't even need the development environment.

**Comment by jcw** [comment]
Good idea, the `!send` command could have a list of pre-defined URLs (e.g. pointing to github) and allow fetch/sending then using the `!s <n>` notation, just like uploads do now.

**Comment by jcw** [comment]
Or there could be a `!dir <url>` command, which grabs the page, parses links in it, and presents a selection dialog to fetch and then sends the text to the attached µC.

Neat side-effect: could allow pointing to a blog post, and "running" the demo(s) listed on that page. Because this is aimed at Forth, the links could be filtered to only those pointing to `*.fs` files.

(from a suggestion by @tve)
