### ISSUE TITLE
panics and fatal errors leave the tty in a bad state

### ISSUE THREAD

**Issue by jcw** [jeelabs/folie#12]
There needs to be a way to recover the original tty state, which readline sets to raw during use.
Haven't figured out how to do that, defer() is not called in main when the app quits unexpectedly.

For now, a way to restore usable tty state on mac/linux is to blindly type `<CR>stty sane<CR>` on the cmdline, when it appears that nothing is happening or being echoed. Then, echo should be back.

**Comment by JohnOH** [comment]
I appear to need the full <CR>stty sane<CR> to get back to normal.

**Comment by jcw** [comment]
Ah, sorry - typo, fixed.

**Comment by jcw** [comment]
I've corrected the cases I know about so far, so that folie exits cleanly.
Any further "panic" messages are (new) bugs.
