### ISSUE TITLE
Refresh available ports list

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/folie#14]
Johns-MacBook-Pro:folie john$ ./folie -v
Select a serial port:
   1 = /dev/cu.Bluetooth-Incoming-Port
   2 = /dev/cu.Bluetooth-Modem
   3 = /dev/cu.usbserial-D

If a null entry is made to the Select a serial port request then rescan for available ports and display updated select request.

**Comment by jcw** [comment]
It's not clear to me how to implement this given the current design.
The workaround doesn't look too cumbersome to me: restart Folie, since it now can exit cleanly.
Closing for now.
