### ISSUE TITLE
exception with a bare "!" on a line

### ISSUE THREAD

**Issue by jcw** [jeelabs/folie#28]
Folie passes everything through which it doesn't understand.
Unfortunately, that includes a bare "!", often caused by forgetting to enter an actual command.
This leads to an infinite unhandled-exception loop, as Mecrisp treats it as a store.

It's probably better to capture all lines starting with "!".
And perhaps pass lines through when they start with a _doubled_ "!!..." ?

**Comment by jcw** [comment]
Not really a bug, more bad handling of incorrect input.

**Comment by JohnOH** [comment]
:-) sounds like a bug to me.
