### ISSUE TITLE
Error with included files (W10)

### ISSUE THREAD

**Issue by doewie** [jeelabs/folie#33]
I made a simple testsetup with 2 files in the same subdir:

dev.fs
```
reset 	\ remove everything from RAM
: hello ( -- ) 
	CR ." hello" 
;
```
exp.fs
```
include dev.fs  
: run ( -- ) 
	hello 
;
```
In Folie:
`!s exp.fs`

result in Folie:
```
[connected to 192.168.1.79:23]
!s exp.fs[J[2K
2> dev.fs 1: reset  \ remove everything from RAM �Mecrisp-Stellaris RA 2.2.7 for STM32F103 by Matthias Koch
2> dev.fs 3:  CR ." hello"   ok.
open : Het systeem kan het opgegeven bestand niet vinden.
Send failed.
```
Just send the dev.fs file ( so no includes ) works fine
In Folie:
` !s dev.fs`

Result in Folie:
```
[connected to 192.168.1.79:23]
!s dev.fs[J[2K
1> dev.fs 1: reset  \ remove everything from RAM �Mecrisp-Stellaris RA 2.2.7 for STM32F103 by Matthias Koch
1> dev.fs 3:  CR ." hello"   ok.
  ok.2K
hello [J[2K
hello ok.
```

**Comment by jcw** [comment]
Could you try changing `dev.fs` slightly?

```
cr cr reset 	\ remove everything from RAM
cr
: hello ( -- ) 
	CR ." hello" 
;
```

There could be a problem with Folie trying to resynchronise after a reset, because it takes a little time and doesn't always end in a proper `ok.` prompt. The above hacks try to work around that.

**Comment by jcw** [comment]
Another way to avoid this issue is to use `forgetram` i.s.o. `reset`. That's a very new feature, though - you may not yet have it in the Mecrisp build you're using.

**Comment by doewie** [comment]
Same problem. My guess is there is a problem in function [includeFile](https://github.com/jeelabs/folie/blob/master/include.go#L16). I added reporting of the filename.
```
func IncludeFile(name string, level int) bool {
	fmt.Println("*****name: ", name) <========== 
	f, err := os.Open(name)
```
Resulting in following. After return from the included file this function tries to open an empty filename.
```
*****name:  exp.fs
IncludeFile  v2.6-4-gd8ca712
*****name:  dev.fs
IncludeFile  v2.6-4-gd8ca712
2> dev.fs 1: �Mecrisp-Stellaris RA 2.2.7 for STM32F103 by Matthias Koch
2> dev.fs 4:  CR ." hello"   ok.
*****name:  <======================= EMPTY FILENAME !!!!!!!
open : Het systeem kan het opgegeven bestand niet vinden.
Send failed.
```

**Comment by doewie** [comment]
my workaround for the time being is ignoring the empty filename. Now everything runs as expected. 
```
...
func IncludeFile(name string, level int) bool {
	if name == "" {
		return true
	}
....
```
By the way, this Folie 2 is a big improvement. Much faster and cleaner output. Just missing the -c option to make a logfile.

**Comment by jcw** [comment]
Aha... could it be that you have a trailing blank on that include line?
I'm spliting on spaces and including everything in between.

I'll think a bit more about the capture option. There is a plan to tie Folie to MQTT, both for its output and for driving it from MQTT (issue #25), but nothing has been worked out yet.

**Comment by doewie** [comment]
that's indeed the case. After removing the (invisible) trailing spaces it's OK. 

Changed [this line](https://github.com/jeelabs/folie/blob/master/include.go#L49) from
`for _, fname := range strings.Split(line[8:], " ") {`
to
`for _, fname := range strings.Split(strings.TrimSpace(line)[8:], " ") {`

now it's ok, even with trailing spaces
