### ISSUE TITLE
unable to edit line with right/left arrows

### ISSUE THREAD

**Issue by doewie** [jeelabs/folie#35]
Running folie 2.7 in raw mode on the USB-port gives a lot of garbage char's. 
f.i. after selection of the COM-port: A bit annoying but workable.
```
Select the serial port:
  1: COM6
? 1[J[2K
```
More serious problem is when editing an existing line. With the cursor at the end of line and press the left arrow, gives a lot of garbage. The only way to edit the line is to type it again.
`[18Ccr ." hello" ;[J[2K`

In folie 1.x everything worked fine.

**Comment by jcw** [comment]
> In folie 1.x everything worked fine.

Aha... that could be a hint. Many thanks for adding this issue.

Could you try when commenting out the two calls to `InsertCRs` in `console.go` ?
Another thing to try (separately) would be to comment out the `Stdout: os.Stdout,` line instead.

**Comment by doewie** [comment]
First one: same problem
Second one: all garbage disappeared and editing is possible.

Tested with these lines:

```
func ConsoleTask() {
	if readline.IsTerminal(1) {
		os.Stdout = InsertCRs(os.Stdout)
	}
	if readline.IsTerminal(2) {
		os.Stderr = InsertCRs(os.Stderr)
	}

	var err error
	config := readline.Config{
		UniqueEditLine: true,
		// Stdout:         os.Stdout,
	}
```

results:

```
  1: COM6
1
Enter '!help' for additional help, or ctrl-d to quit.
[connected to COM6]
```

**Comment by jcw** [comment]
Wonderful - so removing the `Stdout:` config option fixes all the editing funniness in Windows?

**Comment by doewie** [comment]
yep, looks very promising... Will do some more tests

**Comment by doewie** [comment]
I'm pretty sure this issue can be closed. Output now is clean and all editing problems are gone!!
There is another problem however with the USB (Windows related?), but I will open a new issue for that.

**Comment by jcw** [comment]
Many thanks for your testing. I'm not sure what that `Serout:` option was used for in the first place, but can always add it back on MacOS or Linux later, if needed.
