### ISSUE TITLE
include should work with relative paths

### ISSUE THREAD

**Issue by jcw** [jeelabs/folie#38]
Right now, `include <path>` will open the path relative to the current directory. It would be more flexible to open the path relative to the source file containing this `include`.

**Comment by tht** [comment]
+1 for this change

This helps managing projects living outside of the embello repository. Combined with #21 this could form the basics for a simple library management.

**Comment by jcw** [comment]
I'm closing this issue - moving the discussion to #38 to avoid confusion.
