### ISSUE TITLE
A few Win7 issues

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/folie#4]
Hitting enter rather than make a valid selection:

```
C:\Users\John\My Documents\GitHub\folie>folie.exe
<open> Select a serial port:
   0 = COM255
   1 = COM61
←[J←[2K
2016/10/20 11:47:08 strconv.ParseInt: parsing "": invalid syntax
```

If the selection is made '1' without a terminating <enter> then strange EOL characters.

```
C:\Users\John\My Documents\GitHub\folie>folie.exe
<open> Select a serial port:
   0 = COM255
   1 = COM61
1[J←[2K
```

Selecting the appropriate COM61 port produces "[connected]" as normal, first letter of "upload" produces bad characters but command is accepted and then fails to upload:

```
C:\Users\John\My Documents\GitHub\folie>folie.exe
<open> Select a serial port:
   0 = COM255
   1 = COM61
1←[J←[2K
[connected]
upload [J←[2K
  700b ......+
Failed: 1f

Failed: 00
v00
Failed: 1f

Failed: 00
#0000
Failed: 1f

Failed: 00
R .
Failed: 1f

Failed: 00
W .
Failed: 1f

Failed: 1f
E writing: 1/3 ←[J←[2K
Failed: 1f

Failed: 1f

Failed: 1f
2/3
Failed: 1f

Failed: 1f

Failed: 1f
3/3
Failed: 1f

Failed: 1f

Failed: 1f
done.
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼yy
```

BOOT0 is set and reset hit doesn't change what is happening.

**Comment by JohnOH** [comment]
Still issues:
C:\Users\John\My Documents\Github\folie>folie.exe -v
Select a serial port:
   1 = COM255
   2 = COM40
2←[J←[2K
[connected: COM40]
!u f103-blink [J←[2K
  724b >7f.>7f<79+>00>ff<1f
Failed: 1f

Failed: 00
V00 >02>fd<1f
Failed: 1f

Failed: 00
#0000 >92>6d<1f
Failed: 1f

Failed: 00
R >7f<1f>73>8c<79<79W >7f.>7f<79+>43>bc<1f
Failed: 1f
>ff>00<1f
Failed: 1f
E writing: 1/3 >31>ce<1f
Failed: 1f
>08>00>00>00>08<1f
Failed: 1f
>ff>00>50>00>20>45>02>00>08>43>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>0
2>00>08>00>00>00>00>00>00>00>00>00>00>00>00>00>00>00>00>43>02>00>08>43>02>00>08>
00>00>00>00>43>02>00>08>43>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00
>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>0
2>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>
41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00
>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>0
2>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>
41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00
>08>41>02>00>08>41>02>00>08>41>02>00>08>41>02>00>08>89<1f
Failed: 1f
2/3
Failed: 1f

Failed: 1f

Failed: 1f
3/3
Failed: 1f

Failed: 1f

Failed: 1f
done.
recv: "\x1f"
▼recv: "\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f"
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼recv: "\
x1f"
▼recv: "\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f\x1f
\x1f\x1f\x1f"
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼

**Comment by jcw** [comment]
Is this the same F103 µC which works properly from a Mac, or a different µC board?

**Comment by JohnOH** [comment]
Same device.

**Comment by jcw** [comment]
Ok, so it looks like we're not there yet on Windows.
Not the very very latest folie code, from what I can tell from the output.
But that's probably irrelevant here. I'll need to investigate further...

**Comment by jcw** [comment]
Please try another USB interface, if you have one, non-FTDI if possible. That unit may not have been configured properly - at least that's what I ran into here with a BUB3.

**Comment by jcw** [comment]
Update - looks like this hasn't been solved yet - troubles with timing, it appears.
May have to wait until issue #22 has been addressed.

**Comment by jcw** [comment]
This is most likely the same issue as #36, which has been fixed by an update in the `go-serial` package. I'll include the fix in the next Folie cycle. Closing this issue for now.
