### ISSUE TITLE
Syntaxis error (Folie 2.10 on W10 & RasPi)

### ISSUE THREAD

**Issue by doewie** [jeelabs/folie#43]
New in Folie 2.10 (on W10) is a syntaxis error before the serial port select.
After that everything is OK

```
Folie v2.10


? De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist.
1
Enter '!help' for additional help, or ctrl-d to quit.
[connected to COM9]
Mecrisp-Stellaris RA 2.3.3 with M0 core for STM32L053C8 by Matthias Koch
64 KB <jnz> 3239023E ram/flash: 4928 20352 free ok.


```

Running 2.10 on RasPi same result:
```
Folie v2.10
no such file or directory
Select the serial port:
  1: /dev/ttyACM0
  2: /dev/ttyAMA0
? 1
Enter '!help' for additional help, or ctrl-d to quit.
[connected to /dev/ttyACM0]
Mecrisp-Stellaris RA 2.3.3 for STM32F103 by Matthias Koch
128 KB <jnz> 31395E08 ram/flash: 19256 34940 free ok.
```

**Comment by jcw** [comment]
Yikes. Looks like I broke something.

**Comment by doewie** [comment]
If I start Folie with `-p COM9` it's OK. 
So somewhere an unspecified port is not handled properly.

**Comment by jcw** [comment]
This is probably not Windows-related, it just happens that goroutine-order brings out this bug.

I will keep this open for now, it needs to be revisited once I have done a fairly major re-design of the goroutines in Folie to handle some other cases properly (Linux serial re-open fails to re-init properly).

**Comment by jcw** [comment]
I think the Linux case has been fixed, could you do a `git pull` and see how it behaves on Windows?

Note that you may need to re-upload a new image if you're using the USB-driver in Mecrisp. Its back-to-back bug has been fixed, and the workaround has been removed from the latest Folie code.

**Comment by doewie** [comment]
I can/will run a test on W10 tomorrow evening

**Comment by doewie** [comment]
On RasPi everything seems to be OK now. 
Also on W10 the syntaxis error now seems to be disappeared and startup looks good now.
But sometimes the port selection table is not printed. Typing the correct nr. ( for me it's 1) however starts everything as expected:
```
Folie v2.10-test
Select the serial port:

1
Enter '!help' for additional help, or ctrl-d to quit.
[connected to COM9]
Mecrisp-Stellaris RA 2.3.3 with M0 core for STM32L053C8 by Matthias Koch
64 KB <jnz> 3239023E ram/flash: 4928 20352 free ok.
```

**Comment by jcw** [comment]
Ah, thx - yeah, the startup order is still not quite right. Baby steps...

**Comment by jcw** [comment]
Port selection should work better now.

**Comment by doewie** [comment]
I agree. Just tested opening of folie 2.10 on W10 some 20 times with a 100% OK-score. It looks like you have solved this one. Great!
