### ISSUE TITLE
no "ok" prompt in folie 2.12+bluepill

### ISSUE THREAD

**Issue by mvcorrea** [jeelabs/folie#53]
using 
https://github.com/jeelabs/embello/tree/master/explore/1608-forth/suf (usb-common)
It connects but I am unable to get the forth "ok" prompt. 
It works ok with folie 1.X or "screen" connect
previously discussed here
https://github.com/jeelabs/embello/issues/78

**Comment by jcw** [comment]
Did you start folie in raw mode? (`-r` option)

**Comment by mvcorrea** [comment]
hi there,
I forgot this part. 
just perfect.
thanks for your time.

```
osx% ./folie-macos64_v2.14 -r
Select the serial port:
  1: /dev/cu.Bluetooth-Incoming-Port
  2: /dev/cu.usbmodemD5222A31
2
Enter '!help' for additional help, or ctrl-d to quit.
Serial port busy
[connected to /dev/cu.usbmodemD5222A31]
  ok.
3 2 + . 5  ok.
  ok.
```
