### ISSUE TITLE
special command starting with "!"

### ISSUE THREAD

**Issue by jcw** [jeelabs/folie#8]
The current code recognises "upload ..." etc as special cases, using prefix string matching.
It's both long to write interactively and potentially confusing w.r.t. "normal" input.

Idea is to support `!u ...` and `!upload ...` instead, this matches what some traditional Unix utilities do (e.g. "!sh" as shell escape).

As a general convention, this will open the path to many other escapes - to view status, set options, show help, include files, log transcripts, open a socket, etc.

**Comment by JohnOH** [comment]
Provide support for a "!exit" or "!quit" command.

**Comment by jcw** [comment]
Wouldn't `!exit` do the same as ctrl-d or ctrl-c?

I agree that folie does needs to give a hint on startup, perhaps: `Enter "!help" for additional help.`

**Comment by JohnOH** [comment]
Yup

**Comment by jcw** [comment]
Closing this for now. There's a very brief help message when called without cmdline args.

Adding `!h` for help, `!i` for include, `!q` for quit, etc is another task, for another day.
